import { ColorTheme } from '../types'

export const colorThemes: Record<string, ColorTheme> = {
  emerald: {
    name: "Verde Esmeralda",
    primary: "emerald",
    secondary: "teal",
    accent: "cyan",
    gradientFrom: "from-emerald-500/20",
    gradientTo: "to-teal-500/20",
    border: "border-emerald-500/20",
    borderHover: "hover:border-emerald-400/50",
    bg: "bg-emerald-500/10",
    text: "text-emerald-400",
    textGradient: "from-emerald-400 to-teal-500",
    button: "from-emerald-600 to-teal-600",
    buttonHover: "hover:from-emerald-700 hover:to-teal-700",
    shadow: "shadow-emerald-500/25",
    ring: "focus:ring-emerald-500",
    particle: "bg-emerald-400",
  },
  blue: {
    name: "Azul Océano",
    primary: "blue",
    secondary: "indigo",
    accent: "sky",
    gradientFrom: "from-blue-500/20",
    gradientTo: "to-indigo-500/20",
    border: "border-blue-500/20",
    borderHover: "hover:border-blue-400/50",
    bg: "bg-blue-500/10",
    text: "text-blue-400",
    textGradient: "from-blue-400 to-indigo-500",
    button: "from-blue-600 to-indigo-600",
    buttonHover: "hover:from-blue-700 hover:to-indigo-700",
    shadow: "shadow-blue-500/25",
    ring: "focus:ring-blue-500",
    particle: "bg-blue-400",
  },
  purple: {
    name: "Morado Místico",
    primary: "purple",
    secondary: "violet",
    accent: "fuchsia",
    gradientFrom: "from-purple-500/20",
    gradientTo: "to-violet-500/20",
    border: "border-purple-500/20",
    borderHover: "hover:border-purple-400/50",
    bg: "bg-purple-500/10",
    text: "text-purple-400",
    textGradient: "from-purple-400 to-violet-500",
    button: "from-purple-600 to-violet-600",
    buttonHover: "hover:from-purple-700 hover:to-violet-700",
    shadow: "shadow-purple-500/25",
    ring: "focus:ring-purple-500",
    particle: "bg-purple-400",
  },
  red: {
    name: "Rojo Fuego",
    primary: "red",
    secondary: "rose",
    accent: "pink",
    gradientFrom: "from-red-500/20",
    gradientTo: "to-rose-500/20",
    border: "border-red-500/20",
    borderHover: "hover:border-red-400/50",
    bg: "bg-red-500/10",
    text: "text-red-400",
    textGradient: "from-red-400 to-rose-500",
    button: "from-red-600 to-rose-600",
    buttonHover: "hover:from-red-700 hover:to-rose-700",
    shadow: "shadow-red-500/25",
    ring: "focus:ring-red-500",
    particle: "bg-red-400",
  },
  orange: {
    name: "Naranja Vibrante",
    primary: "orange",
    secondary: "amber",
    accent: "yellow",
    gradientFrom: "from-orange-500/20",
    gradientTo: "to-amber-500/20",
    border: "border-orange-500/20",
    borderHover: "hover:border-orange-400/50",
    bg: "bg-orange-500/10",
    text: "text-orange-400",
    textGradient: "from-orange-400 to-amber-500",
    button: "from-orange-600 to-amber-600",
    buttonHover: "hover:from-orange-700 hover:to-amber-700",
    shadow: "shadow-orange-500/25",
    ring: "focus:ring-orange-500",
    particle: "bg-orange-400",
  },
  cyan: {
    name: "Cian Eléctrico",
    primary: "cyan",
    secondary: "teal",
    accent: "sky",
    gradientFrom: "from-cyan-500/20",
    gradientTo: "to-teal-500/20",
    border: "border-cyan-500/20",
    borderHover: "hover:border-cyan-400/50",
    bg: "bg-cyan-500/10",
    text: "text-cyan-400",
    textGradient: "from-cyan-400 to-teal-500",
    button: "from-cyan-600 to-teal-600",
    buttonHover: "hover:from-cyan-700 hover:to-teal-700",
    shadow: "shadow-cyan-500/25",
    ring: "focus:ring-cyan-500",
    particle: "bg-cyan-400",
  },
}
